# Generated by Django 4.2.4 on 2023-11-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_videogame_managers_alter_videogame_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='videogame',
            managers=[
            ],
        ),
    ]
