# Generated by Django 4.2.4 on 2023-11-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_driver_alter_review_product_drivinglicense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivinglicense',
            old_name='licence_number',
            new_name='license_number',
        ),
    ]
