# Generated by Django 4.2.4 on 2023-10-25 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPersonBonusExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120)])),
            ],
        ),
    ]
